<?xml version="1.0" encoding="utf-8"?><Database Name="Final" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-VIJGOTF;Initial Catalog=Final;Integrated Security=True" SettingsObjectName="All_in_one.Properties.Settings" SettingsPropertyName="FinalConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.linq_2" Member="linq_2s">
    <Type Name="linq_2">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CustomerName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ProductName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="OrderedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>